### ISSUE TITLE
Theme.AppCompat.Light.NoActionBar theme support

### ISSUE THREAD

**Issue by kael-moreno** [ming-xi/MXMediaPicker#3]
I have an app that has a theme with parent `Theme.AppCompat.Light.NoActionBar` because I use my own Toolbar.

However, there's a crash error showing this:

```java.lang.RuntimeException: Unable to start activity ComponentInfo{com.interactivex.kotlin.android.debug/tech.mingxi.mediapicker.ui.pages.MediaPickerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference```

Thank you!

**Comment by ArchangelXu** [comment]
@kaelmoreno-cp  Thank you for reporting!
I will check it out tomorrow.

**Comment by ArchangelXu** [comment]
@kaelmoreno-cp Fixed. Please upgrade to 1.0.7 to check it out~

**Comment by kael-moreno** [comment]
@ArchangelXu sure! ill test it. Thank you so much!
