### ISSUE TITLE
Camera Functionality

### ISSUE THREAD

**Issue by kael-moreno** [ming-xi/MXMediaPicker#4]
Hi!

I've tested the camera functionality. It opened the camera, however, I'm having problems with the returned data of the intent.

For normal selection of image/video from storage, I'm getting this:
**Image**
![image](https://user-images.githubusercontent.com/7289423/115198189-5e6c9100-a124-11eb-8c5a-d6538367180e.png)

**Video**
![image](https://user-images.githubusercontent.com/7289423/115198239-6cbaad00-a124-11eb-9a3c-f73a87913a3f.png)

But if I'm using camera (isAllowCamera = true), in `onActivityResult()`, I'm getting the path as null, and the filename is in uri.

**Image Camera**
![image](https://user-images.githubusercontent.com/7289423/115198464-a986a400-a124-11eb-86c6-0393d105b4eb.png)

**Video Camera** 
![image](https://user-images.githubusercontent.com/7289423/115198426-9ecc0f00-a124-11eb-8e40-5b09f20d134d.png)

Thank you!

**Comment by ArchangelXu** [comment]
@kaelmoreno-cp Thanks for asking.
If you look at the document of `getPath` method of class `ResultItem`, you'll see that this method only provides some information and it's not recommanded to use it to read file.
Use `getUri` Instead.

**Comment by kael-moreno** [comment]
Hi @ArchangelXu ! Thank you for immediate response!

I'm using `item.path` to get the FileName, and uri for getting the data. But when I used the camera, the filename is in `item.uri`. Is there a way to get the filename in a same property whether it's from the camera, or from the picker?

Or an identifier if the returned data of intent in onActivityResult came from picking of file or the camera? So I can identify what to use to get the filename: if by item.uri or item.path.

Thank you so much!

**Comment by ArchangelXu** [comment]
Hi @kaelmoreno-cp , I fixed this bug. Please try version 1.0.8.

**Comment by kael-moreno** [comment]
Hi @ArchangelXu ,

Fixed! Thank you!

![image](https://user-images.githubusercontent.com/7289423/115212909-94654180-a133-11eb-93cc-bd8983cad31b.png)
