### ISSUE TITLE
Q: How can i will copy selected file to Internal directory?

### ISSUE THREAD

**Issue by Sharabaddin** [ming-xi/MXMediaPicker#5]
Q: How can i will copy selected file to Internal directory?

**Comment by ArchangelXu** [comment]
emmm... you may use input/outputstream to do that.

**Comment by Sharabaddin** [comment]
@ArchangelXu Sorry but, have u example for supports android 11?

**Comment by ArchangelXu** [comment]
demo is in the project... you can run it on Android 11 emulators

**Comment by Sharabaddin** [comment]
@ArchangelXu thx, but I dont see when i set path for internal save files or directory

**Comment by ArchangelXu** [comment]
@Sharabaddin this library's main function is to provide a way to select files in Android 11. You can read selected files through returned uris, and do whatever you want with these files.
